### ISSUE TITLE
Waffle 4.0 roadmap

### ISSUE THREAD

**Issue by marekkirejczyk** [TrueFiEng/Waffle#405]
Goals for Waffle 4.0:
- Improved speed of test execution 
- Deeper integration with HardHat
- Increased type safety (TypeScript types as first class citizen)

Features:
- [x] Remove JEST support
- [ ] Add `eqBN()` instead of magic `eq`
- [ ] Watch mode (check HardHat plugin)
- [ ] Parallel test execution (Implement in HardHat)
- [x] 100% test coverage against HardHat provider
- [x] Integration with TypeChain out-of-the-box
- [  ] Integration with faster MockProvider (geth or other)

**Comment by pandichef** [comment]
"100% test coverage against HardHat provider"
Does this mean devs will be able to use HardHat Network under the hood of MockProvider as an alternative to Ganache?

**Comment by marekkirejczyk** [comment]
@pandichef That would be the goal, not sure if and when we would be able to achieve it.

**Comment by cktang88** [comment]
Curious why Jest support will be removed?

**Comment by marekkirejczyk** [comment]
JEST didn't get traction, code base grow big, we have to focus on different things (eg HardHat integration)

**Comment by StKostyantin** [comment]
> JEST didn't get traction, code base grow big, we have to focus on different things (eg HardHat integration)

Very sorry. Because many people use jest for testing on a project. And they won't switch to chai only of this library...
I think you could greatly increase the use of your library by changing your development philosophy.
You are making a very cool project, but so far chai is not what I would like to see on my project...

**Comment by paulrberg** [comment]
It would be awesome if https://github.com/EthWorks/Waffle/issues/511 was added on the roadmap for v4.0!

**Comment by PetarKirov** [comment]
Hey @marekkirejczyk, what's the status of 4.0? I can see that you guys have published 4.0.7 versions for the packages, but by default npm still list 3.4.4. Is 4.0.7 "officially" released? If not, what is the plan?

**Comment by PetarKirov** [comment]
Also, when do you plan to upgrade to `@ganache/*^7.4.1`?

**Comment by rzadp** [comment]
@PetarKirov We consider 4.x.x released, but at the same time we're holding off marking as `latest` on npm until we have the [Hardhat Waffle plugin](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-waffle) updated and using Waffle 4.x.x.

We already test the plugin with 4.x.x internally and all our tests are working, but we want to move slowly here.

> Also, when do you plan to upgrade to @ganache/*^7.4.1?

Actually we're on it, so you can expected a release with new ganache next week. We also want to introduce some simple automation for periodically upgrading Ganache version.

**Comment by PetarKirov** [comment]
> @PetarKirov We consider 4.x.x released, but at the same time we're holding off marking as latest on npm until we have the [Hardhat Waffle plugin](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-waffle) updated and using Waffle 4.x.x.

Thanks for the info @rzadp! We tried using `ethereum-waffle@4.0.7` with `@nomiclabs/hardhat-waffle@2.0.3` (despite the warning about peerDependency version mismatch (it wanted `ethereum-waffle@^3.2.0`)) and our tests succeeded without needing any adjustments. We have yet to carefully read the [4.0 migration guide](https://ethereum-waffle.readthedocs.io/en/latest/migration-guides.html#migration-from-waffle-3-4-0-to-waffle-4-0-0-alpha) and review our tests, but things are looking good so far ;)

> We already test the plugin with 4.x.x internally and all our tests are working, but we want to move slowly here.
>
>> Also, when do you plan to upgrade to @ganache/*^7.4.1?
>
> Actually we're on it, so you can expected a release with new ganache next week. We also want to introduce some simple automation for periodically upgrading Ganache version.

Great, keep up the good work! :+1:

**Comment by rzadp** [comment]
For all interested: [Waffle 4 is out](https://twitter.com/TrueFiEng/status/1587127078343909376) 🙂
